# Generated by Django 4.0.5 on 2022-06-13 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fish_type', models.CharField(max_length=225)),
                ('fish_name', models.CharField(max_length=225)),
                ('fish_size', models.FloatField()),
                ('fish_price', models.FloatField()),
            ],
        ),
    ]
