# Generated by Django 4.0.5 on 2022-06-14 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_fish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fish',
            name='fish_price',
        ),
        migrations.AlterField(
            model_name='fish',
            name='fish_size',
            field=models.CharField(max_length=225),
        ),
        migrations.CreateModel(
            name='Fish2',
            fields=[
                ('fish_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='members.fish')),
                ('fish_img', models.FileField(upload_to='images')),
                ('fish_desc', models.TextField()),
                ('available_size', models.CharField(max_length=200)),
                ('fish_price', models.FloatField()),
            ],
            bases=('members.fish',),
        ),
    ]
