# Generated by Django 4.0.5 on 2022-06-15 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_remove_fish_fish_price_alter_fish_fish_size_fish2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fish2',
            name='fish_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
