# Generated by Django 4.0.5 on 2022-06-23 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_fish2_available_qty_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='Product_qty',
            new_name='product_qty',
        ),
    ]
